modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Mrbysco/ThisMatters/issues"
license="MIT"

[[mods]]
modId="thismatters"
version="${file.jarVersion}"
displayName="This Matters"
displayURL="https://www.curseforge.com/minecraft/mc-mods/this-matters"
authors="Mrbysco"
description='''
Allows you to compress organic matter and other items into a single item.
'''
[[dependencies.thismatters]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.thismatters]]
modId="neoforge"
mandatory=true
versionRange="[20.2.86,)"
ordering="NONE"
side="BOTH"