modLoader="javafml"
loaderVersion="[45,)"
issueTrackerURL="https://github.com/Mrbysco/ThisMatters/issues"
license="MIT"

[[mods]]
modId="thismatters"
version="${file.jarVersion}"
displayName="This Matters"
displayURL="https://www.curseforge.com/minecraft/mc-mods/this-matters"
authors="Mrbysco"
description='''
Allows you to compress organic matter and other items into a single item.
'''
[[dependencies.thismatters]]
modId="minecraft"
mandatory=true
versionRange="[1.19.4,1.20)"
ordering="NONE"
side="BOTH"