modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/ThisMatters/issues"
license="MIT"

[[mods]]
modId="thismatters"
version="${file.jarVersion}"
displayName="This Matters"
displayURL="https://www.curseforge.com/minecraft/mc-mods/this-matters"
authors="Mrbysco"
description='''
Allows you to compress organic matter and other items into a single item.
'''
[[dependencies.thismatters]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.thismatters]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.117-beta,)"
ordering="NONE"
side="BOTH"